from app import discover_companies

discover_companies.append_new_companies([
    {"name": 'Aktion Associates', "ats": 'workable', "slug": 'aktion-associates'},
    {"name": 'AlphaSense', "ats": 'greenhouse', "slug": 'alphasense'},
    {"name": 'Apollo.io', "ats": 'greenhouse', "slug": 'apolloio'},
    {"name": 'Arista Networks', "ats": 'smartrecruiters', "slug": 'aristanetworks'},
    {"name": 'Asana', "ats": 'greenhouse', "slug": 'asana'},
    {"name": 'AutoScout24', "ats": 'greenhouse', "slug": 'autoscout24'},
    {"name": 'Babylist', "ats": 'greenhouse', "slug": 'babylist'},
    {"name": 'Bankjoy', "ats": 'ashby', "slug": 'bankjoy'},
    {"name": 'Blend360', "ats": 'smartrecruiters', "slug": 'blend360'},
    {"name": 'Boosted.ai', "ats": 'greenhouse', "slug": 'boostedai'},
    {"name": 'Braze', "ats": 'greenhouse', "slug": 'braze'},
    {"name": 'BuildOps', "ats": 'greenhouse', "slug": 'buildops'},
    {"name": 'Cantina', "ats": 'ashby', "slug": 'cantina'},
    {"name": 'Chainguard', "ats": 'greenhouse', "slug": 'chainguard'},
    {"name": 'CircleCI', "ats": 'greenhouse', "slug": 'circleci'},
    {"name": 'Clutch Technologies', "ats": 'greenhouse', "slug": 'clutch'},
    {"name": 'Clutch Technologies Inc.', "ats": 'greenhouse', "slug": 'clutch'},
    {"name": 'Coalition', "ats": 'greenhouse', "slug": 'coalition'},
    {"name": 'Coalition Technologies ', "ats": 'greenhouse', "slug": 'coalition'},
    {"name": 'Cority', "ats": 'lever', "slug": 'cority'},
    {"name": 'Deep Sky', "ats": 'lever', "slug": 'deepsky'},
    {"name": 'Dialpad', "ats": 'greenhouse', "slug": 'dialpad'},
    {"name": 'Diligent', "ats": 'greenhouse', "slug": 'diligent'},
    {"name": 'Diligent Corporation', "ats": 'greenhouse', "slug": 'diligent'},
    {"name": 'Docker', "ats": 'ashby', "slug": 'docker'},
    {"name": 'Doppel', "ats": 'greenhouse', "slug": 'doppel'},
    {"name": 'Doppel', "ats": 'ashby', "slug": 'doppel'},
    {"name": 'Elation Health', "ats": 'greenhouse', "slug": 'elationhealth'},
    {"name": 'Emburse', "ats": 'lever', "slug": 'emburse'},
    {"name": 'Evismart', "ats": 'greenhouse', "slug": 'evismart'},
    {"name": 'Fable', "ats": 'ashby', "slug": 'fable'},
    {"name": 'Fincentify', "ats": 'ashby', "slug": 'fincentify'},
    {"name": 'Fivetran', "ats": 'greenhouse', "slug": 'fivetran'},
    {"name": 'GoDaddy', "ats": 'greenhouse', "slug": 'godaddy'},
    {"name": 'Hiive', "ats": 'ashby', "slug": 'hiive'},
    {"name": 'Ideogram', "ats": 'ashby', "slug": 'ideogram'},
    {"name": 'Indie Semiconductor', "ats": 'greenhouse', "slug": 'indiesemiconductor'},
    {"name": 'Intellistack', "ats": 'ashby', "slug": 'intellistack'},
    {"name": 'Jetson Home', "ats": 'greenhouse', "slug": 'jetsonhome'},
    {"name": 'Jobgether', "ats": 'lever', "slug": 'jobgether'},
    {"name": 'Kaseya', "ats": 'greenhouse', "slug": 'kaseya'},
    {"name": 'Kogniz', "ats": 'lever', "slug": 'kogniz'},
    {"name": 'Lithic', "ats": 'greenhouse', "slug": 'lithic'},
    {"name": 'Lyft', "ats": 'greenhouse', "slug": 'lyft'},
    {"name": 'MLabs', "ats": 'workable', "slug": 'mlabs'},
    {"name": 'Magical', "ats": 'ashby', "slug": 'magical'},
    {"name": 'Marble Technology', "ats": 'ashby', "slug": 'marble'},
    {"name": 'Maxima', "ats": 'ashby', "slug": 'maxima'},
    {"name": 'Maxima', "ats": 'smartrecruiters', "slug": 'maxima'},
    {"name": 'Meow', "ats": 'ashby', "slug": 'meow'},
    {"name": 'Motus', "ats": 'greenhouse', "slug": 'motus'},
    {"name": 'Mycroft', "ats": 'ashby', "slug": 'mycroft'},
    {"name": 'NexHealth', "ats": 'greenhouse', "slug": 'nexhealth'},
    {"name": 'Nubank', "ats": 'ashby', "slug": 'nubank'},
    {"name": 'Nylas', "ats": 'ashby', "slug": 'nylas'},
    {"name": 'Okta', "ats": 'greenhouse', "slug": 'okta'},
    {"name": 'OpenLoop Health', "ats": 'ashby', "slug": 'openloophealth'},
    {"name": 'Outschool', "ats": 'greenhouse', "slug": 'outschool'},
    {"name": 'Outschool', "ats": 'ashby', "slug": 'outschool'},
    {"name": 'PSL', "ats": 'greenhouse', "slug": 'psl'},
    {"name": 'Parkland', "ats": 'greenhouse', "slug": 'parkland'},
    {"name": 'Passage', "ats": 'ashby', "slug": 'passage'},
    {"name": 'Pinterest', "ats": 'greenhouse', "slug": 'pinterest'},
    {"name": 'PolicyMe', "ats": 'lever', "slug": 'policyme'},
    {"name": 'Promise Robotics', "ats": 'lever', "slug": 'promiserobotics'},
    {"name": 'Ravenwake Games', "ats": 'greenhouse', "slug": 'ravenwakegames'},
    {"name": 'Relay', "ats": 'ashby', "slug": 'relay'},
    {"name": 'Relay', "ats": 'lever', "slug": 'relay'},
    {"name": 'Resmed', "ats": 'smartrecruiters', "slug": 'resmed'},
    {"name": 'Revic', "ats": 'ashby', "slug": 'revic'},
    {"name": 'Robinhood', "ats": 'greenhouse', "slug": 'robinhood'},
    {"name": 'SIA', "ats": 'smartrecruiters', "slug": 'sia'},
    {"name": 'Samsara', "ats": 'greenhouse', "slug": 'samsara'},
    {"name": 'Shakepay', "ats": 'greenhouse', "slug": 'shakepay'},
    {"name": 'ShyftLabs', "ats": 'lever', "slug": 'shyftlabs'},
    {"name": 'Sia', "ats": 'smartrecruiters', "slug": 'sia'},
    {"name": 'Smart', "ats": 'smartrecruiters', "slug": 'smart'},
    {"name": 'Sophos', "ats": 'lever', "slug": 'sophos'},
    {"name": 'Spaceium', "ats": 'greenhouse', "slug": 'spaceium'},
    {"name": 'Syndio', "ats": 'greenhouse', "slug": 'syndio'},
    {"name": 'Synechron', "ats": 'smartrecruiters', "slug": 'synechron'},
    {"name": 'TELUS Digital', "ats": 'ashby', "slug": 'telus-digital'},
    {"name": 'TTEC Digital', "ats": 'lever', "slug": 'ttecdigital'},
    {"name": 'Tailscale', "ats": 'greenhouse', "slug": 'tailscale'},
    {"name": 'Tailwind', "ats": 'ashby', "slug": 'tailwind'},
    {"name": 'Terminal', "ats": 'ashby', "slug": 'terminal'},
    {"name": 'Thanx', "ats": 'greenhouse', "slug": 'thanx'},
    {"name": 'Unblocked', "ats": 'ashby', "slug": 'unblocked'},
    {"name": 'Varicent', "ats": 'greenhouse', "slug": 'varicent'},
    {"name": 'Veracode', "ats": 'greenhouse', "slug": 'veracode'},
    {"name": 'Xsolla', "ats": 'lever', "slug": 'xsolla'},
    {"name": 'ZoomInfo', "ats": 'greenhouse', "slug": 'zoominfo'},
    {"name": 'hireVouch', "ats": 'lever', "slug": 'hirevouch'},
])
